apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - mutating_webhook.yaml
  - validating_webhook.yaml
  - crds.yaml
