apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: sample-cluster-queue
spec:
  namespaceSelector: {} # Selects all namespaces
  resourceGroups:
  - coveredResources: ["cpu", "memory", "pods"]
    flavors:
    - name: default
      resources:
        - name: cpu
          nominalQuota: 2
        - name: memory
          nominalQuota: 4Gi
        - name: pods
          nominalQuota: 5