apiVersion: batch/v1
kind: Job
metadata:
  name: example-08-job
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: sample-local-queue
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
      - name: example-container
        image: busybox:stable
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 30"]
      restartPolicy: Never
