apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
  name: v1beta1.visibility.kueue.x-k8s.io
spec:
  group: visibility.kueue.x-k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: kueue-visibility-server
    namespace: kueue-system
  version: v1beta1
  versionPriority: 100