apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sa.yaml
  - rbac.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - api-service.yaml
  - mutating-webhook.yaml
  - validating-webhook.yaml
  - crds.yaml
