apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
  name: kueue-webhook-server-cert
  namespace: kueue-system